version: "3.9"

services:
  db:
    image: postgres:16
    container_name: social_media_db
    restart: always
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: social_media_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: social_media_web
    command: gunicorn social_media.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
